### PR TITLE
Fix map aspect ratio

### PR DESCRIPTION
**Pull request by alex-s-gardner**
set axis.autolimitaspect = 1 when figure is created. This addresses #37

### CODE REVIEW

**Comment by rafaqz** [comment]
What does `autolimitaspect` do?

**Comment by alex-s-gardner** [comment]
DataAspect uses the currently chosen axis limits and brings the axes into the same aspect ratio. This is the easiest to use with images. A different aspect ratio can only reduce the axis space that is being used, also it necessarily has to break the layout a little bit.
https://docs.makie.org/stable/examples/blocks/axis/index.html#controlling_axis_aspect_ratios

autolimitaspect forces the aspect ratio of the whole axis to be the same
https://docs.makie.org/stable/examples/blocks/axis/index.html#controlling_data_aspect_ratios

**Comment by rafaqz** [comment]
Thanks for the explanation!

**Comment by rafaqz** [comment]
Hahaha I tried it thats so much better, select zooming is actually usable now!

Thanks

**Pull request merged**
