### PR TITLE
[WIP] Bump Makie compat to v0.21

### PR DESCRIPTION
**Pull request by asinghvi17**
This is mainly for testing so I can pull from and potentially fix a branch.

### CODE REVIEW

**Comment by asinghvi17** [comment]
See #82, we should not merge this until that is solved.

**Comment by asinghvi17** [comment]
Try this:
```julia
using Tyler, GLMakie
london = Rect2f(-0.0921, 51.5, 0.04, 0.025)
fig = Figure(); nax = LScene(fig[1, 1]); fig
m = Tyler.Map(london, figure = fig, axis = nax)
fig
```

You can see that the z-fighting begins immediately.  I have a video up on Discord showing that as well, you can update the extent to the France example earlier using:
```julia
france_view = Tyler.Extents.Extent(X = (-21739.258606623473, 586505.0035158572), Y = (6.453166815536934e6, 6.930553746366132e6))
Tyler.update_tiles!(m, france_view)
```
and pan around to see the z-fighting happening.

**Comment by asinghvi17** [comment]
@felixcremer could you try this branch now?  I'm getting better results when I set the z scale to 1 instead of 0, which was done in the last commit.

**Comment by SimonDanisch** [comment]
I mean mwe without Tyler! ;)

**Comment by asinghvi17** [comment]
Screenshot 2024-05-12 at 11 49 33 AM
Is the Tyler web-mercator math different from what is accepted?

**Pull request closed without merging**
