### PR TITLE
use shading enums to remove warnings

### PR DESCRIPTION
**Pull request by rafaqz**
@simon was this enum available in Makie 0.19 or should I fix the version to 0.20 ?

### CODE REVIEW

**Comment by SimonDanisch** [comment]
This is new as of 0.20!

**Comment by rafaqz** [comment]
Ok thanks. Do you think its worth trying to support both 0.19 and 0.20 here, or just switching to 0.20?

**Comment by SimonDanisch** [comment]
I've been in the force updating camp most of the time to optimize maintainer time ;)

**Comment by rafaqz** [comment]
Me to but I get in trouble for it :sweat_smile:

**Comment by rafaqz** [comment]
Haha in the end I also have to downgrade everything to 0.19 because MakieDraw is totally broken on 0.20

**Pull request merged**
