### PR TITLE
Try to make Tyler GeoMakie compatible

### PR DESCRIPTION
**Pull request by felixcremer**
Maybe it would be better to simply use a GeoAxis and let GeoMakie handle the conversion logic, that is currently done in Tyler.

This works when we set the PROJ_RESCALE_FACTOR to 1

This makes the Axis type of the Map object a type parameter so that we can also use a GeoAxis in there. 
The show statements still need to be removed when this is done. 

This also fixes the debug_tiles function

### CODE REVIEW

**Comment by felixcremer** [comment]
This would fix #77

**Comment by lazarusA** [comment]
Could you add a simple example in the docs?

**Comment by asinghvi17** [comment]
@felixcremer should we close this in favour of #90 which also has these commits?

**Comment by felixcremer** [comment]
Yes

**Pull request closed without merging**
