### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by rafaqz**
Some code reorganisation while I get aquainted with new changes.

Mostly grouping like functions and Base/package/tyler interfaces.

Also some file renames like 3d-map.jl and tyler-cam3d.jl to map3d.jl and cam3d.jl, and tiles.jl to tile-cache.jl as thats whats in it now.

### CODE REVIEW

**Comment by lazarusA** [comment]
nice, the only thing failing (segfaults) are those `Observable` tests examples, introduced recently.

**Comment by rafaqz** [comment]
Maybe we can move those tests to the end so the rest run

**Comment by asinghvi17** [comment]
They are already at the end, all the other tests run before them.

**Comment by rafaqz** [comment]
Ok I might manual test the 3d stuff before merging

**Pull request merged**
